### ISSUE TITLE
Explaination

### ISSUE THREAD

**Issue by EmptikBest** [Torom/BotLi#102]
Please explain this:
```
blacklist chessfyBOT
Added chessfyBOT to the blacklist.
Challenging chessfyBOT (+6) as white to bullet ...
Challenge against chessfyBOT has timed out.
chessfyBOT will not be challenged to a new game pair before 2023-06-02 19:25:45.
Challenging chessfyBOT (+6) as white to bullet ...
Challenge against chessfyBOT has timed out.
chessfyBOT will not be challenged to a new game pair before 2023-06-02 19:27:26.
```

I have also blacklisted chessfyBOT in the config,yml

**Comment by Torom** [comment]
Can you post the relevant section from the config please.

The temporary blacklist in the user interface has a delay in matchmaking until the next time the online bots are downloaded. So maximum 30 minutes until the blocked is no longer challenged. For challenges from him, the blacklist takes effect immediately.

But what's going on there anyway? Is this the complete output of BotLi without any lines removed? The opponent should not be challenged twice in a row, when the challenge has expired.

**Comment by EmptikBest** [comment]
Yes, it is the complete output.. One time it kept doing this 22 times in a row until some other bot challenged it.
Here is the relevant section from the config:
`  blacklist:                              # List of users who are not challenged and whose challenges are declined.
  - ElmiChess
  - actual_magnus
  - Annie_archy
  - chessfyBOT`

**Comment by EmptikBest** [comment]
No, I don't run matchmaking with multiple variants, here is the relevant section from the config:
matchmaking:
  initial_time: 60                        # Initial time for matchmaking mode.
  increment: 1                            # Increment time for matchmaking mode.
  rated: true                             # Activate rated games in matchmaking mode.
  timeout: 30                             # Time until a challenge is canceled.
  variants:                               # Chess variants (https://lichess.org/variant) to challenge.
    - standard
#   - chess960
#   - antichess
#   - atomic
#   - crazyhouse
#   - horde
#   - kingOfTheHill
#   - racingKings
#   - threeCheck
# min_rating_diff: 0                      # Minimum rating distance to opponent. (Commenting allowed)
# max_rating_diff: 300                    # Maximum rating distance to opponent. (Commenting allowed)
  delay: 70                               # Time in seconds the bot must be idle before a new challenge is started.
  multiplier: 0                           # Multiplier for calculating timeouts in matchmaking. Higher values lead to a wider range of opponents.

**Comment by Torom** [comment]
```yaml
multiplier: 0
```

is the problem. If you set a multiplier to zero, you of course break the whole timeout calculation. I will check this in the future and not allow it below 1.

**Comment by EmptikBest** [comment]
Yes, I wrote the blacklist before starting BotLi... I'm changing the multiplier to one

**Comment by Torom** [comment]
Can you please post your complete config without the token?

**Comment by EmptikBest** [comment]
here is the config: https://drive.google.com/file/d/1pgcHKdTLM2qIFIdPbm3fMjQvF6sw14e6/view?usp=sharing

**Comment by Torom** [comment]
You got the indentation wrong. The blacklist must not be indented:

```yml
messages:
  # Optional substitution keywords (include curly braces):
  #   {opponent} to insert the opponent's name
  #   {me} to insert our name
  #   {engine} to insert engine name
  #   {cpu} to insert CPU information
  #   {ram} to insert RAM size
  # Any other words in curly braces will be removed.
  greeting: "Hey, I'm running {engine} on an RTX 3080 10GB and 8GiB of RAM. Good luck! Type !help for a list of commands." # Message sent to the opponent at the beginning of a game.
  goodbye: "Good game, see you next time."                                             # Message sent to the opponent after the end of a game.
  greeting_spectators: "Hey, I'm running {engine} on an RTX 3080 10GB and 8GiB of RAM. Type !help for a list of commands." # Message sent to the spectators at the beginning of a game.
  goodbye_spectators: "Thanks for watching."                                           # Message sent to the spectators after the end of a game.

blacklist:                                # List of users who are not challenged and whose challenges are declined.
  - ElmiChess
  - actual_magnus
  - Annie_archy
  - chessfyBOT

books:                                    # Names of the opening books (to be used above in the opening_books section) and paths to the opening books.
  OlisFish: "F:/EmptikBot/OlisFish-220523.bin"
```
