### ISSUE TITLE
Request: Specific white and black books for each TC

### ISSUE THREAD

**Issue by IbaiBuR** [Torom/BotLi#132]
**Is your feature request related to a problem? Please describe.**
No its not, it is something I'd like to see implemented to increase the strength of my bots

**Describe the solution you'd like**
As of now, with all the new changes, we can select books for standard, white, black, bullet, blitz, rapid...

But, in my case, I'd like to be able to choose different books for white and black for an specific TC, in this way:

```
bullet:
  white:
     names:
      ....
  black: 
     names:
     ....
```

Hope this is not very annoying and does not complicate the config too much. Thanks in advance

**Comment by Torom** [comment]
I don't particularly like the way white and black books are defined so far either. The programming effort is also not very complex. But I'm not sure how to get it into the config. The goal is that a simple configuration is still possible. Your proposed structure would bloat the config too much and a simple configuration would not be so trivial anymore. So someone who just wants to use a book for all cases for example.

I am open for suggestions.

**Comment by Torom** [comment]
Something like `TC_COLOR` as key would make sense, but don't know yet if this is the best solution and if the users really get along with it. This would look something like this:

```yaml
  books:
    standard:
      selection: weighted_random
      names:
        - DefaultBook
    bullet_white:
      selection: weighted_random
      names:
        - WhiteBook
    bullet_black:
      selection: weighted_random
      names:
        - BlackBook
```
