### ISSUE TITLE
Request: Accept challenges per TC

### ISSUE THREAD

**Issue by EmptikBest** [Torom/BotLi#133]
**Is your feature request related to a problem? Please describe.**
No, not really, its just that right now I can only accept 1 TC per day (read on to see why)

**Describe the solution you'd like**
If possible, could there be different time controls (max_increment, initial etc) accepted per TC?
For example the section in the config.yml could look like this:
```
challenge:
  bullet:
    concurrency: 1
    with_increment_only: true
#   min_increment: 0
#   max_increment: 180
#   min_initial: 0
#  max_initial 315360000
  blitz:
    concurrency: 1
    with_increment_only: false
#   min_increment: 0
#   max_increment: 180
#   min_initial: 0
#  max_initial 315360000
#   Use the same pattern for 'bullet', 'blitz', 'rapid', 'classical',
#   'antichess', 'atomic', 'chess960', 'crazyhouse', 'horde', 'kingofthehill', 'racingkings' and '3check' as well.
```

This would help me a lot since these days I only accept one TC per day (example 1+0, 3+0, 8+0, 25+0) as if I accept multiple it is possible people play 7+0 and it is still considered blitz..

With this implementation, I will be able to accept 1+0, 3+0, 8+0, 25+0 all at once and it would help me a lot!

**Describe alternatives you've considered**

**Additional context**
If possible and doesn't clutter the config too much, maybe do the same thing with # Append _white or _black to only accept challenges as the specific color.. I do think that can lead to other bots only playing white/black though so that should probably not be added
