### ISSUE TITLE
Lichess sends invalid move

### ISSUE THREAD

**Issue by Torom** [Torom/BotLi#151]
Created from @IbaiBuR

This is the error I got during the game:

```
Exception in thread Thread-913:

Traceback (most recent call last):

  File "/usr/local/lib/python3.12/threading.py", line 1052, in _bootstrap_inner

    self.run()

  File "/game.py", line 71, in run

    updated = self.lichess_game.update(event)

              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/lichess_game.py", line 88, in update

    self.board.push(chess.Move.from_uci(moves[-1]))

  File "/usr/local/lib/python3.12/site-packages/chess/__init__.py", line 2259, in push

    assert piece_type is not None, f"push() expects move to be pseudo-legal, but got {move} in {self.board_fen()}"

AssertionError: push() expects move to be pseudo-legal, but got a1a4 in 3n2k1/2p2ppp/1p6/8/r2BP3/2P2PP1/5K2/5R2
```
Along with the error,  the engine made an stupid move giving up a rook for free (I dont even know why), so, afterwards,  I checked btop (similar to htop) because the server's CPU usage stagnated for some reason, and I saw this:

![Screenshot from 2023-11-22 08-49-06](https://github.com/Torom/BotLi/assets/64355006/f33d7b9b-23ef-40b3-b3fb-fa89e53570a5)

So 2 instances of the engine were runninng at once, for some unknown reason. Even if I am using my own stockfish-derived engine, I do not think the error is related to that, because it never happened to me before.

Some insights about the environment the bot is running in:

- OS: Ubuntu 22.04LTS
- CPU: AMD EPYC 7282, 2 threads used of 4 available
- Dockerized, using python:3.12 base image
- The config file:

```yaml
token: ""         

engines:
  bullet:
    dir: "./engines"
    name: "BlackHole"
    ponder: true
    use_syzygy: true
    silence_stderr: true
    uci_options:
      Threads: 2
      Hash: 256
      Move Overhead: 500
      Experience Book: true
  blitz:                                 
    dir: "./engines"                     
    name: "BlackHole"                    
    ponder: true                         
    use_syzygy: true                     
    silence_stderr: true                 
    uci_options:                         
      Threads: 2                         
      Hash: 256                          
      Move Overhead: 750                 
      Experience Book: true
  rapid:                                 
    dir: "./engines"                     
    name: "BlackHole"                    
    ponder: true                         
    use_syzygy: true                     
    silence_stderr: true                 
    uci_options:                         
      Threads: 2                         
      Hash: 256                          
      Move Overhead: 850
  classical:                             
    dir: "./engines"                      
    name: "BlackHole"                     
    ponder: true                          
    use_syzygy: true                      
    silence_stderr: true                  
    uci_options:                          
      Threads: 2                          
      Hash: 256                           
      Move Overhead: 1000  

syzygy:
  enabled: true                           
  paths:                                  
    - "./engines/syzygy"
  max_pieces: 5                           
  instant_play: true                      

gaviota:
  enabled: false                          
  paths:                                  
    - "/path/to/gaviota"
  max_pieces: 5                           

opening_books:
  enabled: true                           
  priority: 400                           
  books:
    bullet_white:
      selection: weighted_random          
      names:
online_moves:
  opening_explorer:
    enabled: false                      
    priority: 300                       
    use_for_variants: false             
    min_time: 20                        
    timeout: 5                          
    min_games: 5                        
    only_with_wins: false               
    selection: "performance"            
    anti: false                         
#   max_depth: 16                       
#   max_moves: 1                        
  lichess_cloud:
    enabled: false                      
    priority: 200                       
    only_without_book: false            
    min_eval_depth: 10                  
    min_time: 20                        
    timeout: 5                          
#   max_depth: 16                       
#   max_moves: 1                        
  chessdb:
    enabled: false                      
    priority: 100                       
    min_eval_depth: 10                  
    min_time: 20                        
    timeout: 5                          
#   max_depth: 16                       
#   max_moves: 1                        
  online_egtb:
    enabled: true                       
    min_time: 10                        
    timeout: 2                          

offer_draw:
  enabled: true                         
  score: 10                             
  consecutive_moves: 10                 
  min_game_length: 35                   

resign:
  enabled: false                        
  score: -1000                          
  consecutive_moves: 5                  

move_overhead_multiplier: 1.1           

challenge:                               
  concurrency: 1                         
  bullet_with_increment_only: true       
# min_increment: 1                       
  max_increment: 5                       
  min_initial: 60                        
  max_initial: 1800                      
  variants:                              
    - standard
#   - chess960
#   - fromPosition
#   - antichess
#   - atomic
#   - crazyhouse
#   - horde
#   - kingOfTheHill
#   - racingKings
#   - threeCheck
  time_controls:
    - bullet
    - blitz
    - rapid
    - classical
  bot_modes:                              
    - casual                              
    - rated                               
  human_modes:                            
#   - casual                              
#   - rated                               

matchmaking:
  delay: 90                               
  timeout: 30                             
  types:  
    bullet_1:                              
      tc: 1+1                             
      rated: true                         
      variant: standard                   
      weight: 10                          
      multiplier: 20                      
      max_rating_diff: 400
    bullet_2:                              
      tc: 2+1                             
      rated: true                         
      variant: standard                   
      weight: 10                          
      multiplier: 20                      
      max_rating_diff: 400
    blitz_1:                              
      tc:  3+2                           
      rated: true                         
      variant: standard                   
      weight: 10                          
      multiplier: 20                      
      max_rating_diff: 400
    blitz_2:                              
      tc:  5+0                           
      rated: true                         
      variant: standard                   
      weight: 15                          
      multiplier: 20                      
      max_rating_diff: 400
    blitz_3:                              
      tc:  5+3                           
      rated: true                         
      variant: standard                   
      weight: 10                          
      multiplier: 20                      
      max_rating_diff: 400
    rapid_1:                              
      tc:  5+5                           
      rated: true                         
      variant: standard                   
      weight: 10                          
      multiplier: 20                      
      max_rating_diff: 400
    rapid_2:                              
      tc:  8+2                           
      rated: true                         
      variant: standard                   
      weight: 10                          
      multiplier: 20                      
      max_rating_diff: 400
    rapid_3:                              
      tc:  10+3                           
      rated: true                         
      variant: standard                   
      weight: 10                          
      multiplier: 20                      
      max_rating_diff: 400
    classical_1:                              
      tc:  25+1                           
      rated: true                         
      variant: standard                   
      weight: 15                          
      multiplier: 20                      
      max_rating_diff: 400
      
messages:
  greeting: "Hey, I'm {me} running {engine}. Good luck! Type !help for a list of commands." 
  goodbye: "Good game {opponent} , see you next time."                                      
  greeting_spectators: "Hey I'm {me} running {engine}. Type !help for a list of commands." 
  goodbye_spectators: "Thanks for watching {me} vs {opponent}!"                             
```

The book part is missing since I prefer to keep it private and also the blacklist/whitelist one.
