### ISSUE TITLE
Botli gets time outed quickly on heroku

### ISSUE THREAD

**Issue by RoboTicCoders** [Torom/BotLi#28]
I don't what the problem is but it automatically gets time outed

**Comment by Torom** [comment]
Can you maybe explain what you mean? How am I supposed to be able to help you like this?

**Comment by RoboTicCoders** [comment]
alright i made my bot play a game with a another bot and it quickly got time outed.I want to know what is the best settings for bullet??

**Comment by RoboTicCoders** [comment]
i don't understand why it gets quickly time outed

**Comment by Torom** [comment]
By "time outed" do you mean that the bot lost on time? Was it a 30+0 game? Without increment this happens, Lichess has a certain lag that gets worse when the moves are played faster and faster, it is often pure luck who wins on time.

And besides, some of your configuration is pretty much nonsense. I would not set the `Move Overhead` in the `uci_options` so high, this leads to bad moves of Stockfish when playing without increment. The `Threads` are way too high, you don`t get so many CPUs on Heroku, the `Hash` is very small.

**Comment by RoboTicCoders** [comment]
thanks

**Comment by Torom** [comment]
```yaml
    lichess_cloud:
      enabled: true                        # Activate online moves from Lichess cloud eval.
      min_eval_depth: 50                   # Minimum evaluation depth.
      min_time: 50                         # Time the bot must have at least to use the online move.
      timeout: 5                           # Time the server has to respond.
      max_depth: 100                       # Half move max depth. (Comment this line for max depth)
```

You fucked up your `lichess_cloud` config. This is the default:
```yaml
    lichess_cloud:
      enabled: false                      # Activate online moves from Lichess cloud eval.
      min_eval_depth: 10                  # Minimum evaluation depth.
      min_time: 40                        # Time the bot must have at least to use the online move.
      timeout: 5                          # Time the server has to respond.
#     max_depth: 16                       # Half move max depth. (Comment this line for max depth)
```
